version: 2

# commands:
#   cache_restore:
#     steps:
#       - restore_cache:
#           key: gopkg-v1-{{ .Branch }}-{{ checksum "go.sum" }}
#           paths:
#             - /go/src/github.com/hortonworks/aws-iam-authenticator-service/vendor
#   cache_save:
#     steps:
#       - save_cache:
#           key: gopkg-v1-{{ .Branch }}-{{ checksum "go.sum" }}
#           paths:
#             - /go/src/github.com/hortonworks/aws-iam-authenticator-service/vendor

jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/hortonworks/aws-iam-authenticator-service
    steps:
      - checkout
      # - cache_restore
      - run:
          name: build
          command: make build
      # - cache_save

workflows:
  version: 2
  build:
    jobs:
      - build
