replicaCount: 1

image:
  repository: aws-iam-authenticator-service
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 21735

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: nginx
  }
  path: /aws-iam-authenticator-service
  hosts:
    - cluster.local
